apiVersion: v1
kind: Service
metadata:
  name: {{ include "furiosa-npu-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "furiosa-npu-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.operator.metricsPort }}
  selector:
    {{- include "furiosa-npu-operator.selectorLabels" . | nindent 4 }}
