apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "furiosa-device-plugin.name" . }}-config-cm
  namespace: {{ .Values.namespace | default "kube-system" }}
data:
  config.yaml: |
    partitioning: {{ .Values.config.partitioning | default "generic" }}
    debugMode: {{ .Values.config.debugMode | default "false" }}
    disabledDeviceUUIDs:
{{ toYaml (default dict .Values.config.disabledDeviceUUIDs) | indent 6 }}
